name: "友链申请"
title: "feat(friends): 加入"
description: "为 CLN Blog 申请友链"
labels: "新友链,等待处理"
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已添加 [CLN Blog](https://blog.adclosenn.top) 的友情链接"
      required: true
    - label: "[CLN Blog](https://blog.adclosenn.top) 不添加 **采集站**、**纯搬运站点**、**论坛类站点** 等非 **个人博客** 类型的站点"
      required: true
    - label: "站点目前可以在 **中国大陆区域** 正常访问"
      required: true
    - label: "申请的友链是独立域名，非 `github.io`、`vercel.app` 等第三方域名"
      required: true
    - label: "若申请时或日后有违反上述规定，CLN Blog 有权**自行删除且不进行通知**"
       required: true
       
- type: input
  id: "yml-2"
  attributes:
    label: "站点名称"
    description: "网站所使用的标题。请勿输入过长的名称，否则可能会被删除部分内容"
  validations:
    required: true
- type: input
  id: "yml-3"
  attributes:
    label: "站点描述"
    description: "简单描述你的网站是什么。一般 5-15 个字符即可"
  validations:
    required: true
- type: input
  id: "yml-4"
  attributes:
    label: "站点 URL"
    description: "填写你的网站的 URL"
  validations:
    required: true
- type: input
  id: "yml-5"
  attributes:
    label: "站点图片"
    description: "填写你的网站的 `favicon.ico` 或者你认为合适的、鲜明的、有辨识性的图片。请勿提供 NSFW 图片，否则将直接拒绝申请"
  validations:
    required: true
- type: textarea
  id: "yml-6"
  attributes:
    label: "其他"
    placeholder: "其他想说的可以在这里说"
  validations:
    required: false
